refs #3020 introduce exceptions arg alterr and alterr_diag to hold de…
qorelanguage/module-pgsql pull request #47
Opened 2018-10-02 14:36 UTC by pvanek

…tailed error code and description as it is described in:

https://www.postgresql.org/docs/current/static/errcodes-appendix.html

Example:

```
  err : "DBI:PGSQL:TRANSACTION-ERROR"
  desc : "connection to PostgreSQL database server lost while in a transaction; transaction has been lost"
  arg : hash: (2 members)
    alterr : "57P01"
    alterr_diag : "terminating connection due to administrator command"
```

2018-10-02 14:42 UTC, davidnich approved these changes
looks good - please add a relnote

2018-10-03 07:20 UTC, pvanek commented
ok, updated with docs/relnotes and test

2018-10-03 08:23 UTC, sejvlond requested changes

2018-10-03 08:23 UTC, sejvlond commented on src/QorePGConnection.cpp
> +            char* sql_state = PQresultErrorField(res, PG_DIAG_SQLSTATE);
const char * + message from https://www.postgresql.org/docs/9.0/static/libpq-exec.html

also below

2018-10-03 08:59 UTC, sejvlond requested changes

2018-10-03 08:59 UTC, sejvlond commented on src/QorePGConnection.cpp
> +const QoreHashNode* QorePGConnection::getExceptionArg(PGresult *res, ExceptionSink *xsink) {
`const PGresult *res`

return `QoreHashNode*`

2018-10-03 09:11 UTC, merged